site_name: MoyWiki
site_url: https://moychen.github.io/moywiki/
site_author: moychen

# Repository
repo_name: moychen/moywiki
repo_url: https://github.com/moychen/moywiki
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 MoyChen

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
        linenums: false
    - toc:
        permalink: true
        anchorlink: True
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    

theme:
    name: mkdocs
    favicon: img/favicon.ico
    # logo: 'images/logo.svg'
    language: "zh"
    features:
        # - navigation.instant
        - navigation.sections
        - navigation.tabs
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
        - scheme: slate
          primary: red
          accent: red
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono

nav:
    - Home: index.md
    - Language:
        - C/C++: CC++/Index.md
        - Golang: Golang/Index.md
    - About: about.md



